In [20]:
s = [[123,12,123,12,33],[],[]]

In [2]:
import numpy as np

In [6]:
n = np.arange(27)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [7]:
type(n)

numpy.ndarray

In [11]:
n.size

27

In [14]:
n.reshape(3,int(n.size/3))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [15]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [18]:
r = np.asarray([[123,12,123,12,33],[],[]], dtype = object)
print(r)
'''
VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences
(which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated.
If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
r = np.asarray([[123,12,123,12,33],[],[]])
'''

[list([123, 12, 123, 12, 33]) list([]) list([])]


"\nVisibleDeprecationWarning: Creating an ndarray from ragged nested sequences\n(which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated.\nIf you meant to do this, you must specify 'dtype=object' when creating the ndarray.\nr = np.asarray([[123,12,123,12,33],[],[]])\n"

In [21]:
type(s)

list

In [22]:
type(r)

numpy.ndarray

In [ ]:
'''
And as I mentioned earlier Numpy is a base library for all the libraries.

Such as Pandas and also OpenCV which is an image processing library.

So Pandas data frames are based on Numpy arrays and OpenCV objects are based on Numpy arrays.
'''